### PR TITLE
History management

### PR DESCRIPTION
**Pull request by aman11s**
Feature added
- History page
- Add to history
- Remove from history

### CODE REVIEW

**Review by dev-enforced — APPROVED** [review]
Good work @aman11s on history management. Especially the history disable button when action is taking place

**Review by MiryalaAkshitha — APPROVED** [review]
Modular code
Good job done with history management

**Review by vashnavichauhan1825 — APPROVED** [review]
Well structured code and everything looks good to me ready to merged

**Review by shashikantmaurya0007 — COMMENTED** [review]
Looks good to be merged

**Pull request merged**
